info:
  name: spring-boot-mybatis-dev
  contact: spring-boot-mybatis-dev

server:
  port: 8001
  address: localhost
  sessionTimeout: 30
  contextPath: /boot-mybatis
  
spring:
  datasource:
    url: jdbc:mysql://192.168.72.1/mavenpractice?characterEncoding=UTF-8&useUnicode=true&useSSL=true
    driverClassName: com.mysql.jdbc.Driver
    username: mavenpractice
    password: mavenpractice
    
#MyBatis
mybatis:
  typeAliasesPackage: com.vivebest.spring.boot.mybatis.entity
  mapperLocations: classpath:/sqlmap/**/*-Mapper.xml
  configLocation: classpath:/config/mybatis-config.xml