info:
  name: spring-boot-mybatis-default
  contact: spring-boot-mybatis-default

server:
  port: 8080

spring:
  application:
    name: spring-boot-mybatis
  profiles:
    active: dev

logging:
  config: classpath:config/log4j2.xml